=== hap-server/hap-server/schemas/config.schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"version": "0.10.0",
	"title": "hap-server configuration",
	"type": "object",
	"properties": {
		"hostname": {
			"type": "string",
			"description": "The hostname to advertise.",
			"minLength": 1
		},
		"data-path": {
			"type": "string",
			"description": "Path to store data if different from the directory containing this configuration file."
		},
		"plugin-path": {
			"oneOf": [
				{
					"type": "string",
					"description": "Path to a plugin/plugins."
				},
				{
					"type": "array",
					"items": {
						"type": "string",
						"description": "Path to a plugin/plugins."
					}
				}
			]
		},
		"listen": {
			"oneOf": [
				{
					"type": "array",
					"description": "Addresses to listen on.",
					"minItems": 1,
					"items": {
						"oneOf": [
							{
								"$ref": "#/properties/listen/definitions/any"
							},
							{
								"$ref": "#/properties/listen/definitions/net"
							},
							{
								"$ref": "#/properties/listen/definitions/unix"
							}
						]
					}
				},
				{
					"$ref": "#/properties/listen/definitions/any"
				}
			],
			"definitions": {
				"any": {
					"oneOf": [
						{
							"$ref": "#/properties/listen/definitions/net-port"
						},
						{
							"$ref": "#/properties/listen/definitions/net-ipv6"
						},
						{
							"$ref": "#/properties/listen/definitions/net-ipv4"
						},
						{
							"$ref": "#/properties/listen/definitions/unix-string"
						}
					]
				},
				"key": {
					"oneOf": [
						{
							"$ref": "#/properties/listen/definitions/net-ipv6"
						},
						{
							"$ref": "#/properties/listen/definitions/net-ipv4"
						},
						{
							"$ref": "#/properties/listen/definitions/unix-string"
						}
					]
				},
				"net": {
					"type": "array",
					"items": [
						{
							"type": "string",
							"description": "Address type.",
							"enum": [
								"net"
							]
						},
						{
							"type": "string",
							"description": "IPv6/IPv4 address to listen on.",
							"oneOf": [
								{
									"format": "ipv6"
								},
								{
									"format": "ipv4"
								}
							]
						},
						{
							"type": "number",
							"description": "Port number to listen on.",
							"minimum": 1,
							"maximum": 65565
						}
					]
				},
				"unix": {
					"type": "array",
					"items": [
						{
							"type": "string",
							"description": "Address type",
							"enum": [
								"unix"
							]
						},
						{
							"type": "string",
							"description": "Path to listen on as a UNIX socket."
						}
					]
				},
				"net-port": {
					"type": "number",
					"description": "A port number to listen on with all IPv6/IPv4 addresses.",
					"minimum": 1,
					"maximum": 65565
				},
				"net-ipv6": {
					"type": "string",
					"description": "An IPv6 address and port number to listen on.",
					"pattern": "^\\[(([0-9a-fA-F]{1,4}:){7,7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:)|fe80:(:[0-9a-fA-F]{0,4}){0,4}%[0-9a-zA-Z]{1,}|::(ffff(:0{1,4}){0,1}:){0,1}((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])|([0-9a-fA-F]{1,4}:){1,4}:((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9]))\\]:\\d+"
				},
				"net-ipv4": {
					"type": "string",
					"description": "An IPv4 address and port number to listen on.",
					"pattern": "^((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\\.){3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9]):\\d+"
				},
				"unix-string": {
					"type": "string",
					"description": "The path to listen on as a UNIX socket.",
					"pattern": "^(unix\\:|.{0,2}\/).*"
				}
			}
		},
		"listen-https": {
			"type": "object",
			"description": "HTTPS options for listening addresses.",
			"propertyNames": {
				"$ref": "#/properties/listen/definitions/key"
			},
			"patternProperties": {
				".*": {
					"$ref": "#/properties/listen-https/definitions/pem-file-paths"
				}
			},
			"definitions": {
				"pem-file-paths": {
					"oneOf": [
						{
							"type": "string",
							"description": "Path to a certificate and private key."
						},
						{
							"type": "array",
							"description": "Paths to a certificate and private key.",
							"items": {
								"type": "string",
								"description": "Path to a certificate and/or private key."
							}
						}
					]
				}
			}
		},
		"listen-https+request-client-certificate": {
			"description": "HTTPS addresses to request a client certificate for.",
			"oneOf": [
				{
					"type": "array",
					"items": {
						"$ref": "#/properties/listen/definitions/any"
					}
				},
				{
					"type": "object",
					"propertyNames": {
						"$ref": "#/properties/listen/definitions/key"
					},
					"patternProperties": {
						".*": {
							"$ref": "#/properties/listen-https/definitions/pem-file-paths"
						}
					}
				}
			]
		},
		"listen-https+require-client-certificate": {
			"type": "object",
			"description": "HTTPS addresses to require a client certificate for.",
			"propertyNames": {
				"$ref": "#/properties/listen/definitions/key"
			},
			"patternProperties": {
				".*": {
					"$ref": "#/properties/listen-https/definitions/pem-file-paths"
				}
			}
		},
		"listen-https+crl": {
			"type": "object",
			"description": "HTTPS addresses and paths to certificate revocation lists.",
			"propertyNames": {
				"$ref": "#/properties/listen/definitions/key"
			},
			"patternProperties": {
				".*": {
					"type": "string",
					"description": "Path to a certificate revocation list."
				}
			}
		},
		"listen-https+passphrase": {
			"type": "object",
			"description": "HTTPS addresses and passphrases to use to decrypt private keys.",
			"propertyNames": {
				"$ref": "#/properties/listen/definitions/key"
			},
			"patternProperties": {
				".*": {
					"type": "string",
					"description": "Passphrase to use to decrypt private keys."
				}
			}
		},
		"plugins": {
			"type": "object",
			"description": "Plugins configuration.",
			"properties": {
				"*": {
					"description": "Default plugin configuration."
				}
			},
			"patternProperties": {
				".*": {
					"oneOf": [
						{
							"type": "boolean",
							"description": "Plugin enabled/disabled."
						},
						{
							"$ref": "#/properties/plugins/definitions/plugin-configuration"
						}
					]
				}
			},
			"definitions": {
				"plugin-configuration": {
					"type": "object",
					"description": "Plugin configuration.",
					"properties": {
						"accessory-discovery": {
							"$ref": "#/properties/plugins/definitions/accessory-discovery"
						},
						"accessory-setup": {
							"$ref": "#/properties/plugins/definitions/accessory-setup"
						},
						"server-plugins": {
							"$ref": "#/properties/plugins/definitions/server-plugins"
						}
					}
				},
				"accessory-discovery": {
					"description": "Accessory discovery handlers configuration.",
					"properties": {
						"*": {
							"description": "Default accessory discovery handler configuration."
						}
					},
					"patternProperties": {
						".*": {
							"oneOf": [
								{
									"type": "boolean",
									"description": "Accessory discovery handler enabled/disabled."
								},
								{
									"$ref": "#/properties/plugins/definitions/accessory-discovery-configuration"
								}
							]
						}
					}
				},
				"accessory-discovery-configuration": {
					"type": "object",
					"description": "Accessory discovery configuration."
				},
				"accessory-setup": {
					"description": "Accessory setup handlers configuration.",
					"properties": {
						"*": {
							"description": "Default accessory setup handler configuration."
						}
					},
					"patternProperties": {
						".*": {
							"oneOf": [
								{
									"type": "boolean",
									"description": "Accessory setup handler enabled/disabled."
								},
								{
									"$ref": "#/properties/plugins/definitions/accessory-setup-configuration"
								}
							]
						}
					}
				},
				"accessory-setup-configuration": {
					"type": "object",
					"description": "Accessory setup handler configuration."
				},
				"server-plugins": {
					"description": "Server plugins configuration.",
					"properties": {
						"*": {
							"description": "Default server plugin configuration."
						}
					},
					"patternProperties": {
						".*": {
							"oneOf": [
								{
									"type": "boolean",
									"description": "Server plugin enabled/disabled."
								},
								{
									"$ref": "#/properties/plugins/definitions/server-plugin-configuration"
								}
							]
						}
					}
				},
				"server-plugin-configuration": {
					"type": "object",
					"description": "Server plugin configuration."
				}
			}
		},
		"bridge": {
			"type": "object",
			"properties": {
				"name": {
					"type": "string",
					"description": "Name to advertise the bridge as.",
					"minLength": 1,
					"default": "Homebridge"
				},
				"username": {
					"type": "string",
					"description": "Device ID to advertise the bridge as. This must be unique to the local network and any other network you and any shared users use.",
					"pattern": "^([0-9a-fA-F]{2}:){5}[0-9a-fA-F]{2}$"
				},
				"port": {
					"type": "number",
					"description": "Port number to listen on for the bridge's HAP server.",
					"minimum": 1,
					"maximum": 65565
				},
				"pin": {
					"type": "string",
					"description": "Setup code to use when pairing the bridge with HomeKit.",
					"pattern": "^[0-9]{3}-[0-9]{2}-[0-9]{3}$",
					"not": {
						"enum": [
							"000-00-000",
							"111-11-111",
							"222-22-222",
							"333-33-333",
							"444-44-444",
							"555-55-555",
							"666-66-666",
							"777-77-777",
							"888-88-888",
							"999-99-999",
							"123-45-678",
							"876-54-321"
						]
					}
				}
			}
		},
		"accessories": {
			"type": "array",
			"description": "Accessories to add to Homebridge.",
			"items": {
				"allOf": [
					{
						"type": "object",
						"properties": {
							"accessory": {
								"type": "string",
								"description": "Identifier of the Homebridge plugin accessory.",
								"minLength": 1
							},
							"name": {
								"type": "string",
								"description": "Name of the accessory.",
								"minLength": 1
							},
							"uuid_base": {
								"type": "string",
								"description": "Additional information to use when generating the accessory's UUID."
							}
						},
						"required": [
							"accessory",
							"name"
						]
					},
					{
						"$ref": "homebridge/homebridge-accessory.schema.json"
					}
				]
			}
		},
		"platforms": {
			"type": "array",
			"description": "Accessory platforms to add to Homebridge.",
			"items": {
				"allOf": [
					{
						"type": "object",
						"properties": {
							"platform": {
								"type": "string",
								"description": "Identifier of the Homebridge plugin accessory platform.",
								"minLength": 1
							},
							"uuid_base": {
								"type": "string",
								"description": "Additional information to use when generating the accessory UUIDs."
							}
						},
						"required": [
							"platform"
						]
					},
					{
						"$ref": "homebridge/homebridge-platform.schema.json"
					}
				]
			}
		},
		"bridges": {
			"type": "array",
			"description": "HAP bridge configuration",
			"items": {
				"oneOf": [
					{
						"type": "string",
						"description": "Reference to another configuration file",
						"pattern": "^include:.*$"
					},
					{
						"type": "object",
						"description": "Reference to another configuration file",
						"properties": {
							"include": {
								"type": "string",
								"description": "Reference to another configuration file"
							}
						},
						"required": [
							"include"
						],
						"additionalProperties": false
					},
					{
						"$ref": "bridge.schema.json"
					}
				]
			}
		},
		"accessories2": {
			"type": "array",
			"description": "Accessory configuration",
			"items": {
				"oneOf": [
					{
						"type": "string",
						"description": "Reference to another configuration file",
						"pattern": "^include:.*$"
					},
					{
						"type": "object",
						"description": "Reference to another configuration file",
						"properties": {
							"include": {
								"type": "string",
								"description": "Reference to another configuration file"
							}
						},
						"required": [
							"include"
						],
						"additionalProperties": false
					},
					{
						"$ref": "accessory.schema.json"
					}
				]
			}
		},
		"platforms2": {
			"type": "array",
			"description": "Platform configuration",
			"items": {
				"oneOf": [
					{
						"type": "string",
						"description": "Reference to another configuration file",
						"pattern": "^include:.*$"
					},
					{
						"type": "object",
						"description": "Reference to another configuration file",
						"properties": {
							"include": {
								"type": "string",
								"description": "Reference to another configuration file"
							}
						},
						"required": [
							"include"
						],
						"additionalProperties": false
					},
					{
						"$ref": "platform.schema.json"
					}
				]
			}
		},
		"automation-triggers": {
			"type": "object",
			"description": "Automation trigger configuration",
			"patternProperties": {
				".*": {
					"oneOf": [
						{
							"type": "string",
							"description": "Reference to another configuration file",
							"pattern": "^include:.*$"
						},
						{
							"type": "object",
							"description": "Reference to another configuration file",
							"properties": {
								"include": {
									"type": "string",
									"description": "Reference to another configuration file"
								}
							},
							"required": [
								"include"
							],
							"additionalProperties": false
						},
						{
							"$ref": "automation-trigger.schema.json"
						}
					]
				}
			}
		},
		"automation-conditions": {
			"type": "object",
			"description": "Automation conditions configuration",
			"patternProperties": {
				".*": {
					"oneOf": [
						{
							"type": "string",
							"description": "Reference to another configuration file",
							"pattern": "^include:.*$"
						},
						{
							"type": "object",
							"description": "Reference to another configuration file",
							"properties": {
								"include": {
									"type": "string",
									"description": "Reference to another configuration file"
								}
							},
							"required": [
								"include"
							],
							"additionalProperties": false
						},
						{
							"$ref": "automation-condition.schema.json"
						}
					]
				}
			}
		},
		"automation-actions": {
			"type": "object",
			"description": "Automation action configuration",
			"patternProperties": {
				".*": {
					"oneOf": [
						{
							"type": "string",
							"description": "Reference to another configuration file",
							"pattern": "^include:.*$"
						},
						{
							"type": "object",
							"description": "Reference to another configuration file",
							"properties": {
								"include": {
									"type": "string",
									"description": "Reference to another configuration file"
								}
							},
							"required": [
								"include"
							],
							"additionalProperties": false
						},
						{
							"$ref": "automation-action.schema.json"
						}
					]
				}
			}
		},
		"automations": {
			"type": "array",
			"description": "Automation configuration",
			"items": {
				"oneOf": [
					{
						"type": "string",
						"description": "Reference to another configuration file",
						"pattern": "^include:.*$"
					},
					{
						"type": "object",
						"description": "Reference to another configuration file",
						"properties": {
							"include": {
								"type": "string",
								"description": "Reference to another configuration file"
							}
						},
						"required": [
							"include"
						],
						"additionalProperties": false
					},
					{
						"$ref": "automation.schema.json"
					}
				]
			}
		}
	},
	"additionalProperties": false
}

=== hap-server/hap-server/example-config/config.json
{
    "listen": 8082,

    "plugin-path": [
        "../example-plugins/dist"
    ],
    "data-path": ".",

    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },

    "platforms": [
    ],

    "bridges": [
        {
            "name": "Bridge #2",
            "username": "00:00:00:00:00:02",
            "pin": "031-45-154",
            "accessories": [
                ["virtual-switches", "VirtualSwitch", "Switch #1"]
            ],
            "port": 8081
        }
    ],

    "accessories2": [
        {
            "plugin": "virtual-switches",
            "accessory": "VirtualSwitch",
            "name": "Switch #1"
        },
        {
            "plugin": "fake-accessories",
            "accessory": "Television",
            "name": "Television"
        }
    ],

    "platforms2": [
        {
            "plugin": "virtual-switches",
            "platform": "VirtualSwitches",
            "switches": [
                "Switch #2",
                "Switch #3",
                "Switch #4"
            ]
        }
    ]
}
